title: "Poésie & Écrits"
author: htmlpoet
lang: fr-FR

# Exclure des fichiers du build final
exclude:
  - README.md

# Configuration pour la pagination
plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/" # MODIFIÉ

# --- NOUVELLE SECTION ---
# Définir des valeurs par défaut pour des fichiers spécifiques
defaults:
  -
    scope:
      path: "_posts"  # Cible UNIQUEMENT les fichiers dans le dossier _posts
      type: "posts"
    values:
      layout: "post"  # Optionnel mais recommandé : tous vos posts utiliseront ce layout
      permalink: /blog/:title/ # MODIFIÉ

# Umunami section
collections:
  chronicles:
    output: true
    permalink: /umunami/chronicles/:path/